### ISSUE TITLE
Can you make the license clearer?

### ISSUE THREAD

**Issue by ifraixedes** [taskrabbit/empujar#3]
Hi,
Thanks to release this project under MIT.

Can you make the license more explicit mentioning it in the README of adding a LICENSE file?

Thanks!

**Comment by evantahler** [comment]
TaskRabbit uses the Apache 2 License for our open source projects.  I've added that here https://github.com/taskrabbit/empujar/commit/f0e285d79a33d380e443394ab655c4024bb88647

Thanks!

**Comment by ifraixedes** [comment]
Ah, sorry I thought that was MIT because `package.json` has set it.

Can you update `package.json`,  just to be consistent, too?
https://github.com/taskrabbit/empujar/blob/master/package.json#L33

Thanks

**Comment by evantahler** [comment]
Sure thing! Thanks!

https://github.com/taskrabbit/empujar/commit/cae2561bedfba4e1984634e0d3caf19b3e374aee
